### ISSUE TITLE
Paper

### ISSUE THREAD

**Issue by ajayknagaraj** [LiyouZhou/SolarCell#1]
Can you please link the papers from where you modeled this SolarCell?

**Comment by LiyouZhou** [comment]
http://pveducation.org/pvcdrom/characterisation/double-diode-model It is a double diode model. I solve the differential equation by a simple line search method.

**Comment by ajayknagaraj** [comment]
Any other resource?

**Comment by LiyouZhou** [comment]
I can't name any papers specifically. this is a widely accepted model. You are welcome to look around: https://scholar.google.co.uk/scholar?q=double+diode+model&btnG=&hl=en&as_sdt=0%2C5&as_vis=1.
